/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSymptomsIndexRouteImport } from './routes/app.symptoms.index'
import { Route as AppPatientsIndexRouteImport } from './routes/app.patients.index'
import { Route as AppDiagnosesIndexRouteImport } from './routes/app.diagnoses.index'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as AppSymptomsNewRouteImport } from './routes/app.symptoms.new'
import { Route as AppSymptomsIdRouteImport } from './routes/app.symptoms.$id'
import { Route as AppPatientsNewRouteImport } from './routes/app.patients.new'
import { Route as AppPatientsIdRouteImport } from './routes/app.patients.$id'
import { Route as AppDiagnosesIdRouteImport } from './routes/app.diagnoses.$id'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminMlRouteImport } from './routes/app.admin.ml'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSymptomsIndexRoute = AppSymptomsIndexRouteImport.update({
  id: '/symptoms/',
  path: '/symptoms/',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsIndexRoute = AppPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => AppRoute,
} as any)
const AppDiagnosesIndexRoute = AppDiagnosesIndexRouteImport.update({
  id: '/diagnoses/',
  path: '/diagnoses/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppSymptomsNewRoute = AppSymptomsNewRouteImport.update({
  id: '/symptoms/new',
  path: '/symptoms/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSymptomsIdRoute = AppSymptomsIdRouteImport.update({
  id: '/symptoms/$id',
  path: '/symptoms/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsNewRoute = AppPatientsNewRouteImport.update({
  id: '/patients/new',
  path: '/patients/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsIdRoute = AppPatientsIdRouteImport.update({
  id: '/patients/$id',
  path: '/patients/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDiagnosesIdRoute = AppDiagnosesIdRouteImport.update({
  id: '/diagnoses/$id',
  path: '/diagnoses/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminMlRoute = AppAdminMlRouteImport.update({
  id: '/admin/ml',
  path: '/admin/ml',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/ml': typeof AppAdminMlRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/diagnoses/$id': typeof AppDiagnosesIdRoute
  '/app/patients/$id': typeof AppPatientsIdRoute
  '/app/patients/new': typeof AppPatientsNewRoute
  '/app/symptoms/$id': typeof AppSymptomsIdRoute
  '/app/symptoms/new': typeof AppSymptomsNewRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/diagnoses/': typeof AppDiagnosesIndexRoute
  '/app/patients/': typeof AppPatientsIndexRoute
  '/app/symptoms/': typeof AppSymptomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app': typeof AppIndexRoute
  '/app/admin/ml': typeof AppAdminMlRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/diagnoses/$id': typeof AppDiagnosesIdRoute
  '/app/patients/$id': typeof AppPatientsIdRoute
  '/app/patients/new': typeof AppPatientsNewRoute
  '/app/symptoms/$id': typeof AppSymptomsIdRoute
  '/app/symptoms/new': typeof AppSymptomsNewRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/diagnoses': typeof AppDiagnosesIndexRoute
  '/app/patients': typeof AppPatientsIndexRoute
  '/app/symptoms': typeof AppSymptomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/ml': typeof AppAdminMlRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/diagnoses/$id': typeof AppDiagnosesIdRoute
  '/app/patients/$id': typeof AppPatientsIdRoute
  '/app/patients/new': typeof AppPatientsNewRoute
  '/app/symptoms/$id': typeof AppSymptomsIdRoute
  '/app/symptoms/new': typeof AppSymptomsNewRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/diagnoses/': typeof AppDiagnosesIndexRoute
  '/app/patients/': typeof AppPatientsIndexRoute
  '/app/symptoms/': typeof AppSymptomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/'
    | '/app/admin/ml'
    | '/app/admin/users'
    | '/app/diagnoses/$id'
    | '/app/patients/$id'
    | '/app/patients/new'
    | '/app/symptoms/$id'
    | '/app/symptoms/new'
    | '/app/admin/'
    | '/app/diagnoses/'
    | '/app/patients/'
    | '/app/symptoms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/app'
    | '/app/admin/ml'
    | '/app/admin/users'
    | '/app/diagnoses/$id'
    | '/app/patients/$id'
    | '/app/patients/new'
    | '/app/symptoms/$id'
    | '/app/symptoms/new'
    | '/app/admin'
    | '/app/diagnoses'
    | '/app/patients'
    | '/app/symptoms'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/'
    | '/app/admin/ml'
    | '/app/admin/users'
    | '/app/diagnoses/$id'
    | '/app/patients/$id'
    | '/app/patients/new'
    | '/app/symptoms/$id'
    | '/app/symptoms/new'
    | '/app/admin/'
    | '/app/diagnoses/'
    | '/app/patients/'
    | '/app/symptoms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/symptoms/': {
      id: '/app/symptoms/'
      path: '/symptoms'
      fullPath: '/app/symptoms/'
      preLoaderRoute: typeof AppSymptomsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patients/': {
      id: '/app/patients/'
      path: '/patients'
      fullPath: '/app/patients/'
      preLoaderRoute: typeof AppPatientsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/diagnoses/': {
      id: '/app/diagnoses/'
      path: '/diagnoses'
      fullPath: '/app/diagnoses/'
      preLoaderRoute: typeof AppDiagnosesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/admin'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/symptoms/new': {
      id: '/app/symptoms/new'
      path: '/symptoms/new'
      fullPath: '/app/symptoms/new'
      preLoaderRoute: typeof AppSymptomsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/symptoms/$id': {
      id: '/app/symptoms/$id'
      path: '/symptoms/$id'
      fullPath: '/app/symptoms/$id'
      preLoaderRoute: typeof AppSymptomsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patients/new': {
      id: '/app/patients/new'
      path: '/patients/new'
      fullPath: '/app/patients/new'
      preLoaderRoute: typeof AppPatientsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patients/$id': {
      id: '/app/patients/$id'
      path: '/patients/$id'
      fullPath: '/app/patients/$id'
      preLoaderRoute: typeof AppPatientsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/diagnoses/$id': {
      id: '/app/diagnoses/$id'
      path: '/diagnoses/$id'
      fullPath: '/app/diagnoses/$id'
      preLoaderRoute: typeof AppDiagnosesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/ml': {
      id: '/app/admin/ml'
      path: '/admin/ml'
      fullPath: '/app/admin/ml'
      preLoaderRoute: typeof AppAdminMlRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAdminMlRoute: typeof AppAdminMlRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppDiagnosesIdRoute: typeof AppDiagnosesIdRoute
  AppPatientsIdRoute: typeof AppPatientsIdRoute
  AppPatientsNewRoute: typeof AppPatientsNewRoute
  AppSymptomsIdRoute: typeof AppSymptomsIdRoute
  AppSymptomsNewRoute: typeof AppSymptomsNewRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppDiagnosesIndexRoute: typeof AppDiagnosesIndexRoute
  AppPatientsIndexRoute: typeof AppPatientsIndexRoute
  AppSymptomsIndexRoute: typeof AppSymptomsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAdminMlRoute: AppAdminMlRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppDiagnosesIdRoute: AppDiagnosesIdRoute,
  AppPatientsIdRoute: AppPatientsIdRoute,
  AppPatientsNewRoute: AppPatientsNewRoute,
  AppSymptomsIdRoute: AppSymptomsIdRoute,
  AppSymptomsNewRoute: AppSymptomsNewRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppDiagnosesIndexRoute: AppDiagnosesIndexRoute,
  AppPatientsIndexRoute: AppPatientsIndexRoute,
  AppSymptomsIndexRoute: AppSymptomsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
